const imageInput=document.querySelector("#image"),preview=document.querySelector("#preview"),runButton=document.querySelector("#run"),statusEl=document.querySelector("#status"),drop=document.querySelector("#drop"),results=document.querySelector("#results"),summary=document.querySelector("#summary");let selectedFile=null;
function status(text,busy=false){statusEl.textContent=text;statusEl.classList.toggle("busy",busy)}
function previewFile(){if(!selectedFile||!selectedFile.type.startsWith("image/")){runButton.disabled=true;preview.hidden=true;return}preview.src=URL.createObjectURL(selectedFile);preview.hidden=false;runButton.disabled=false;status("READY")}
imageInput.addEventListener("change",()=>{selectedFile=imageInput.files?.[0]||null;previewFile()});drop.addEventListener("dragover",e=>{e.preventDefault();drop.classList.add("dragging")});drop.addEventListener("dragleave",()=>drop.classList.remove("dragging"));drop.addEventListener("drop",e=>{e.preventDefault();drop.classList.remove("dragging");selectedFile=e.dataTransfer.files?.[0]||null;previewFile()});
async function resizeForAnalysis(file){const bitmap=await createImageBitmap(file),maxSide=1800,scale=Math.min(1,maxSide/Math.max(bitmap.width,bitmap.height)),canvas=document.createElement("canvas");canvas.width=Math.max(1,Math.round(bitmap.width*scale));canvas.height=Math.max(1,Math.round(bitmap.height*scale));canvas.getContext("2d",{alpha:false}).drawImage(bitmap,0,0,canvas.width,canvas.height);return new Promise((resolve,reject)=>canvas.toBlob(b=>b?resolve(b):reject(new Error("Could not prepare image")),"image/jpeg",.88))}
function readDataUrl(blob){return new Promise((resolve,reject)=>{const r=new FileReader();r.onload=()=>resolve(r.result);r.onerror=()=>reject(r.error||new Error("Could not read image"));r.readAsDataURL(blob)})}
function esc(v=""){return String(v).replaceAll("&","&amp;").replaceAll("<","&lt;").replaceAll(">","&gt;").replaceAll('"',"&quot;").replaceAll("'","&#039;")}
async function copy(text,button){await navigator.clipboard.writeText(text);const old=button.textContent;button.textContent="COPIED";setTimeout(()=>button.textContent=old,900)}
function card(item,i){const el=document.createElement("article");el.className="card";el.innerHTML=`<div class="card-head"><div><span class="num">0${i+1}</span><h3>${esc(item.concept_title)}</h3></div><span class="badge">${esc(item.content_type)}</span></div><p class="use"><strong>Buyer use:</strong> ${esc(item.buyer_use_case)}</p><p class="change"><strong>Creative change:</strong> ${esc(item.creative_change_summary)}</p><div class="prompt-box"><div class="box-head"><span>MASTER PROMPT</span><button class="copy">COPY</button></div><pre>${esc(item.prompt)}</pre></div><div class="prompt-box muted"><div class="box-head"><span>NEGATIVE / FAILURE AVOIDANCE</span><button class="copy">COPY</button></div><pre>${esc(item.negative_prompt)}</pre></div><div class="meta"><span>Aspect: ${esc(item.aspect_ratio)}</span><span>Copy space: ${esc(item.copy_space)}</span></div>`;const buttons=el.querySelectorAll("button.copy");buttons[0].addEventListener("click",e=>copy(item.prompt,e.currentTarget));buttons[1].addEventListener("click",e=>copy(item.negative_prompt,e.currentTarget));return el}
runButton.addEventListener("click",async()=>{if(!selectedFile)return;try{runButton.disabled=true;status("ANALYZING",true);const image=await readDataUrl(await resizeForAnalysis(selectedFile));const res=await fetch("./api/prompt",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({image,asset_type:document.querySelector("#assetType").value,preferred_aspect:document.querySelector("#aspect").value,notes:document.querySelector("#notes").value})});const data=await res.json();if(!res.ok||!data.ok)throw new Error(data.error||"Prompt compilation failed");document.querySelector("#referenceSummary").textContent=data.result.reference_summary;document.querySelector("#commercialIntent").textContent=data.result.commercial_intent;document.querySelector("#policyNotes").replaceChildren(...data.result.policy_notes.map(x=>{const li=document.createElement("li");li.textContent=x;return li}));document.querySelector("#modelBadge").textContent=`Model: ${data.model}`;document.querySelector("#cards").replaceChildren(...data.result.opportunities.map(card));summary.hidden=false;results.hidden=false;status("5 PROMPTS READY");results.scrollIntoView({behavior:"smooth",block:"start"})}catch(err){status("ERROR");alert(err instanceof Error?err.message:String(err))}finally{runButton.disabled=!selectedFile}});
