const imageInput=document.querySelector('#image'),preview=document.querySelector('#preview'),run=document.querySelector('#run'),statusEl=document.querySelector('#status'),drop=document.querySelector('#drop'),summary=document.querySelector('#summary'),results=document.querySelector('#results');let file=null;
const setStatus=(t,b=false)=>{statusEl.textContent=t;statusEl.classList.toggle('busy',b)};
async function prepareImage(f){const b=await createImageBitmap(f),max=1800,s=Math.min(1,max/Math.max(b.width,b.height)),c=document.createElement('canvas');c.width=Math.max(1,Math.round(b.width*s));c.height=Math.max(1,Math.round(b.height*s));c.getContext('2d',{alpha:false}).drawImage(b,0,0,c.width,c.height);return await new Promise((res,rej)=>c.toBlob(x=>x?res(x):rej(new Error('image preparation failed')),'image/jpeg',.88))}
const dataUrl=b=>new Promise((res,rej)=>{const r=new FileReader();r.onload=()=>res(r.result);r.onerror=()=>rej(r.error||new Error('image read failed'));r.readAsDataURL(b)});
const esc=v=>String(v??'').replaceAll('&','&amp;').replaceAll('<','&lt;').replaceAll('>','&gt;').replaceAll('"','&quot;').replaceAll("'",'&#039;');
function showFile(){if(!file||!file.type.startsWith('image/')){run.disabled=true;preview.hidden=true;return}preview.src=URL.createObjectURL(file);preview.hidden=false;run.disabled=false;setStatus('READY')}
imageInput.addEventListener('change',()=>{file=imageInput.files?.[0]||null;showFile()});drop.addEventListener('dragover',e=>{e.preventDefault();drop.classList.add('dragging')});drop.addEventListener('dragleave',()=>drop.classList.remove('dragging'));drop.addEventListener('drop',e=>{e.preventDefault();drop.classList.remove('dragging');file=e.dataTransfer.files?.[0]||null;showFile()});
async function copyText(text,btn){await navigator.clipboard.writeText(text);const old=btn.textContent;btn.textContent='COPIED';setTimeout(()=>btn.textContent=old,900)}
function makeCard(o,i){const el=document.createElement('article');el.className='card';el.innerHTML=`<div class="card-head"><div><span class="num">0${i+1}</span><h3>${esc(o.concept_title)}</h3></div><span class="badge">${esc(o.content_type)}</span></div><p class="use"><strong>Buyer use:</strong> ${esc(o.buyer_use_case)}</p><p class="change"><strong>Creative change:</strong> ${esc(o.creative_change_summary)}</p><div class="prompt-box"><div class="box-head"><span>MASTER PROMPT</span><button class="copy">COPY</button></div><pre>${esc(o.prompt)}</pre></div><div class="prompt-box muted"><div class="box-head"><span>NEGATIVE / FAILURE AVOIDANCE</span><button class="copy">COPY</button></div><pre>${esc(o.negative_prompt)}</pre></div><div class="meta"><span>Aspect: ${esc(o.aspect_ratio)}</span><span>Copy space: ${esc(o.copy_space)}</span></div>`;const bs=el.querySelectorAll('button.copy');bs[0].onclick=e=>copyText(o.prompt,e.currentTarget);bs[1].onclick=e=>copyText(o.negative_prompt,e.currentTarget);return el}
run.addEventListener('click',async()=>{if(!file)return;run.disabled=true;setStatus('ANALYZING',true);try{const image=await dataUrl(await prepareImage(file));const r=await fetch('./api/prompt',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({image,asset_type:document.querySelector('#assetType').value,preferred_aspect:document.querySelector('#aspect').value,notes:document.querySelector('#notes').value})});const d=await r.json();if(!r.ok||!d.ok)throw new Error(d.error||'Prompt compilation failed');document.querySelector('#referenceSummary').textContent=d.result.reference_summary;document.querySelector('#commercialIntent').textContent=d.result.commercial_intent;document.querySelector('#policyNotes').replaceChildren(...d.result.policy_notes.map(x=>{const li=document.createElement('li');li.textContent=x;return li}));document.querySelector('#modelBadge').textContent=`Model: ${d.model}`;document.querySelector('#cards').replaceChildren(...d.result.opportunities.map(makeCard));summary.hidden=false;results.hidden=false;setStatus('5 PROMPTS READY');results.scrollIntoView({behavior:'smooth',block:'start'})}catch(e){setStatus('ERROR');alert(e instanceof Error?e.message:String(e))}finally{run.disabled=!file}});